landingPage=https://www.automationexercise.com/
LandingPageTitle=Automation Exercise
HomeItem=  Home
loginItem= Signup / Login
headerFormTitle=New User Signup!
headerFormTitle2=Login to your account
AllProductsItem=ALL PRODUCTS
ItemPrice=Rs. 500
ItemName=  Blue Top
ItemCategory=Category: Women > TopsBlue top
ItemAvailability= Availability:
ItemCondition= Condition:
ItemBrand= Brand: